
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model coupon
 * 
 */
export type coupon = Prisma.couponModel
/**
 * Model order_items
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type order_items = Prisma.order_itemsModel
/**
 * Model orders
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type orders = Prisma.ordersModel
/**
 * Model payment
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type payment = Prisma.paymentModel
/**
 * Model product_categories
 * 
 */
export type product_categories = Prisma.product_categoriesModel
/**
 * Model product_types
 * 
 */
export type product_types = Prisma.product_typesModel
/**
 * Model products
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type products = Prisma.productsModel
/**
 * Model profiles
 * 
 */
export type profiles = Prisma.profilesModel
/**
 * Model users
 * 
 */
export type users = Prisma.usersModel
/**
 * Model verification
 * 
 */
export type verification = Prisma.verificationModel
