// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

// Debug: print warning when DATABASE_URL is not set
if (process.env.DATABASE_URL) {
  // Use debug level to avoid noisy logs in typical run output
  // This intentionally avoids printing the full URL (secrets)
  console.debug('DATABASE_URL: ', process.env.DATABASE_URL);
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
