
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  coupon: 'coupon',
  order_items: 'order_items',
  orders: 'orders',
  payment: 'payment',
  product_categories: 'product_categories',
  product_types: 'product_types',
  products: 'products',
  profiles: 'profiles',
  users: 'users',
  verification: 'verification'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CouponScalarFieldEnum = {
  id: 'id',
  code: 'code',
  discount_value: 'discount_value',
  discount_type: 'discount_type',
  expiration_date: 'expiration_date',
  is_active: 'is_active',
  updated_at: 'updated_at'
} as const

export type CouponScalarFieldEnum = (typeof CouponScalarFieldEnum)[keyof typeof CouponScalarFieldEnum]


export const Order_itemsScalarFieldEnum = {
  id: 'id',
  order_id: 'order_id',
  product_id: 'product_id',
  quantity: 'quantity',
  price_at_order: 'price_at_order',
  updated_at: 'updated_at'
} as const

export type Order_itemsScalarFieldEnum = (typeof Order_itemsScalarFieldEnum)[keyof typeof Order_itemsScalarFieldEnum]


export const OrdersScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  total_amount: 'total_amount',
  shipping_address: 'shipping_address',
  status: 'status',
  coupon_id: 'coupon_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type OrdersScalarFieldEnum = (typeof OrdersScalarFieldEnum)[keyof typeof OrdersScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  order_id: 'order_id',
  payment_method: 'payment_method',
  amount_paid: 'amount_paid',
  transaction_id: 'transaction_id',
  status: 'status',
  paid_at: 'paid_at',
  updated_at: 'updated_at'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const Product_categoriesScalarFieldEnum = {
  id: 'id',
  type_id: 'type_id',
  name: 'name',
  updated_at: 'updated_at'
} as const

export type Product_categoriesScalarFieldEnum = (typeof Product_categoriesScalarFieldEnum)[keyof typeof Product_categoriesScalarFieldEnum]


export const Product_typesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  updated_at: 'updated_at'
} as const

export type Product_typesScalarFieldEnum = (typeof Product_typesScalarFieldEnum)[keyof typeof Product_typesScalarFieldEnum]


export const ProductsScalarFieldEnum = {
  id: 'id',
  type_id: 'type_id',
  category_id: 'category_id',
  name: 'name',
  price: 'price',
  thumbnail: 'thumbnail',
  dt_storage: 'dt_storage',
  is_available: 'is_available',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type ProductsScalarFieldEnum = (typeof ProductsScalarFieldEnum)[keyof typeof ProductsScalarFieldEnum]


export const ProfilesScalarFieldEnum = {
  user_id: 'user_id',
  address: 'address',
  phone: 'phone',
  create_at: 'create_at'
} as const

export type ProfilesScalarFieldEnum = (typeof ProfilesScalarFieldEnum)[keyof typeof ProfilesScalarFieldEnum]


export const UsersScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  first_name: 'first_name',
  last_name: 'last_name',
  type: 'type',
  is_verified: 'is_verified',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const VerificationScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  hash_code: 'hash_code',
  expired_at: 'expired_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type VerificationScalarFieldEnum = (typeof VerificationScalarFieldEnum)[keyof typeof VerificationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull'
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

